# Generated by Django 5.2.5 on 2025-09-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_attendanceevent_created_at2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioncategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='fee',
            new_name='fees_student_fc5df7_idx',
            old_name='api_fee_student_ac1287_idx',
        ),
        migrations.AlterUniqueTogether(
            name='collectioncategory',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='attendanceevent',
            table='attendance_events',
        ),
        migrations.AlterModelTable(
            name='attendancerecord',
            table='attendance_records',
        ),
        migrations.AlterModelTable(
            name='eventsetting',
            table='event_settings',
        ),
        migrations.AlterModelTable(
            name='fee',
            table='fees',
        ),
        migrations.AlterModelTable(
            name='institute',
            table='institutes',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='paymentsubmission',
            table='payment_submissions',
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='system',
            table='systems',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usersystems',
            table='user_systems',
        ),
    ]
